repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.7.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        exclude: ^(docs/cookbooks/|community_usecase/)  # Ignore files under docs/cookbooks and community_usecase
      - id: ruff-format
        exclude: ^(docs/cookbooks/|community_usecase/)  # Ignore files under docs/cookbooks and community_usecase

  - repo: local
    hooks:
      - id: mypy
        name: Check mypy
        entry: mypy --namespace-packages -p owl
        language: python
        types: [python]
        pass_filenames: false
        require_serial: true
        exclude: ^(docs/cookbooks/|community_usecase/)  # Ignore files under docs/cookbooks and community_usecase

  - repo: local
    hooks:
    - id: check-license
      name: Check License
      entry: python licenses/update_license.py . licenses/license_template.txt 
      language: system
      types: [python]
      exclude: ^(docs/cookbooks/|community_usecase/)  # Ignore files under docs/cookbooks and community_usecase

  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in pyproject.toml
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
      - tomli  # for python_version < '3.11'
