name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - test-docker-build
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    # Only run on main repo on and PRs that match the main repo.
    if: |
      github.repository == 'camel-ai/owl' &&
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,amd64'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .container/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mugglejinx/owl:latest
            mugglejinx/owl:${{ github.sha }}
          cache-from: type=registry,ref=mugglejinx/owl:buildcache
          cache-to: type=registry,ref=mugglejinx/owl:buildcache,mode=max 